"""Downforce and drag.

CLAUDE.md rules out live CFD, so aerodynamics arrive either as constant
coefficients or as a precomputed speed-indexed lookup table. Both are
handled here behind one interface; the solver never knows which it has.
"""

from __future__ import annotations

import numpy as np

from .config import AeroSpec


class AeroModel:
    """Aerodynamic forces for one car class at one air density.

    ``ClA`` and ``CdA`` fold the coefficient and reference area together,
    which is how published racing-car aero data is usually quoted and avoids
    having to agree on a frontal-area convention between classes.
    """

    def __init__(self, spec: AeroSpec, rho: float | None = None):
        self.spec = spec
        self.rho = float(spec.rho if rho is None else rho)
        if spec.map is not None:
            table = np.asarray(spec.map, dtype=float)
            self._v = table[:, 0]
            self._cla = table[:, 1]
            self._cda = table[:, 2]
            self._bal = table[:, 3]
        else:
            self._v = None
            self._cla = float(spec.cla)
            self._cda = float(spec.cda)
            self._bal = float(spec.balance_front)

    # -- coefficients ----------------------------------------------------
    def cla(self, v):
        """Downforce coefficient x area at speed ``v`` (m^2)."""
        if self._v is None:
            return np.full_like(np.asarray(v, dtype=float), self._cla) \
                if np.ndim(v) else self._cla
        return np.interp(v, self._v, self._cla)

    def cda(self, v):
        """Drag coefficient x area at speed ``v`` (m^2)."""
        if self._v is None:
            return np.full_like(np.asarray(v, dtype=float), self._cda) \
                if np.ndim(v) else self._cda
        return np.interp(v, self._v, self._cda)

    def balance_front(self, v):
        """Fraction of total downforce carried by the front axle."""
        if self._v is None:
            return np.full_like(np.asarray(v, dtype=float), self._bal) \
                if np.ndim(v) else self._bal
        return np.interp(v, self._v, self._bal)

    # -- forces ----------------------------------------------------------
    def downforce(self, v):
        """Vertical load generated by the bodywork (N, positive downwards)."""
        v = np.asarray(v, dtype=float) if np.ndim(v) else float(v)
        return 0.5 * self.rho * self.cla(v) * v * v

    def drag(self, v):
        """Aerodynamic drag (N, always opposing motion)."""
        v = np.asarray(v, dtype=float) if np.ndim(v) else float(v)
        return 0.5 * self.rho * self.cda(v) * v * v

    def efficiency(self, v):
        """Lift-to-drag ratio -- the single number that trades speed for grip."""
        return self.cla(v) / self.cda(v)

    def at_density(self, rho: float) -> "AeroModel":
        """Same shape, different air. Hot days cost downforce and drag alike."""
        return AeroModel(self.spec, rho=rho)

    def __repr__(self) -> str:
        kind = "map" if self._v is not None else "constant"
        return f"AeroModel({kind}, rho={self.rho:.3f})"
